#!/usr/bin/env python

from storz.decompress import digest_firehose_tree
from firehose.report import Analysis
from monomoy.core import db
import json
import sys

r = Analysis.from_xml(open(sys.argv[1], 'r'))
print json.dumps(digest_firehose_tree(r))

#db.reports.insert({
#
#})
