#!/usr/bin/env python

from storz.decompress import digest_firehose_tree
from firehose.report import Analysis
from atlantic.actions import upload_log

import sys


r = Analysis.from_xml(open(sys.argv[2], 'r'))
# Just make sure it works
print upload_log(sys.argv[1], sys.argv[2])
