#!/bin/bash
# Copyright (c) Paul Tagliamonte <paultag@debian.org>, 2013
# under the terms & conditions of storz.
set -e


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PATH="$PATH:${DIR}/../wrappers/"

for file in `find . -name "*bz2"`; do
    storz-buildd-log-parser $file
done
